### ISSUE TITLE
Cannot read '_rev' of undefined while calling req.session.destroy

### ISSUE THREAD

**Issue by JoePotentier** [solzimer/session-pouchdb-store#4]
I'm having an issue destroying this session from my local pouchdb instance. Any ideas why?

![Screen Shot 2020-07-15 at 3 56 33 PM](https://user-images.githubusercontent.com/9673684/87602189-c7b20600-c6b3-11ea-819b-18576b8a1cf5.png)

![Screen Shot 2020-07-15 at 3 52 37 PM](https://user-images.githubusercontent.com/9673684/87602066-90dbf000-c6b3-11ea-91d9-1814f5642fce.png)

**Comment by solzimer** [comment]
Your pull request has been merged. Thanks @JoePotentier
